#cloud-config
package_upgrade: true
packages:
  - nginx
  - openjdk-8-jre

write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    content: |
     server {
     listen 80 default_server;
     root /var/www/html;
     index index.html index.htm index.nginx-debian.html;
     server_name _;
     location / {
     auth_basic "Access deny. Type your password";
     auth_basic_user_file /etc/nginx/.htpasswd;
     proxy_pass http://127.0.0.1:8080/;
     proxy_set_header Authorization "";
     }}
  - owner: www-data:www-data
    path: /etc/nginx/.htpasswd
    content: |
     user01:$apr1$.S4y9MKV$UTT43eHyJsnULFpGmFcq11

runcmd:
  - sudo mkdir TEST
  - wget https://github.com/AlexViki/ansible_devops_create_vm_azure/archive/master.zip -P /TEST/
  - wget https://pkg.jenkins.io/debian-stable/binary/jenkins_2.190.3_all.deb -P /TEST/
#- sudo apt-get update
#- sudo apt-get upgrade
#- sudo apt-get install openjdk-8-jre -y
#- sudo apt-get install nginx -y
#- [ wget, -q, -O, -P, /1_test https://pkg.jenkins.io/debian/jenkins-ci.org.key ]
#| sudo apt-key add -
#- sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
#- sudo apt-get update
#- sudo apt-get install jenkins -y
#- service nginx restart >> /tmp/install.log

#runcmd:
#    - [ sudo, -Hu, ubuntu, sh, -c, 'grep "cloud-init.*running"  /var/log/cloud-init.log > ~/runcmd.log' ]
#    - [ sudo, -Hu, ubuntu, sh, -c, 'read up sleep < /proc/uptime; echo $(date): runcmd up at $up | tee -a ~/runcmd.log' ]
#    - [ sudo, -Hu, ubuntu, sh, -c, *user_setup ]

#cloud-config

#apt_update: true
#packages:
# - git
#write_files:
# - content: |
#      #!/bin/bash
#      echo "A Script!" >& /tmp/script.out
#    permissions: "0755"
#    path: /tmp/script.sh
#runcmd:
#- /tmp/script.sh
#- git clone https://github.com/onecloud/consuming_lab